extends: spectral:oas

rules:
  # Disable validation of examples for non-JSON media types (like jsonl)
  # because Spectral tries to parse them as JSON and fails on multi-line/concatenated JSON
  oas3-valid-media-example: off

